import numpy as np
import matplotlib.pyplot as plt

# 读取数据文件
for i in range(8):
    values1 = np.load(f"expert_grads_L0_FFN0_{i}_nabs.npy", allow_pickle=True)
    values2 = np.load(f"expert_grads_L0_FFN1_{i}_nabs.npy", allow_pickle=True)
    values3 = np.load(f"expert_grads_L1_FFN0_{i}_nabs.npy", allow_pickle=True)
    values4 = np.load(f"expert_grads_L1_FFN1_{i}_nabs.npy", allow_pickle=True)
    # values5 = np.load(f"expert_grads_L2_FFN0_{i}_nabs.npy", allow_pickle=True)
    # values6 = np.load(f"expert_grads_L2_FFN1_{i}_nabs.npy", allow_pickle=True)
    # values7 = np.load(f"expert_grads_L3_FFN0_{i}_nabs.npy", allow_pickle=True)
    # values8 = np.load(f"expert_grads_L3_FFN1_{i}_nabs.npy", allow_pickle=True)
    
    plt.figure()
    plt.plot(values1, label='L0_FFN0_na', color='red', linestyle='--')
    plt.plot(values2, label='L0_FFN1_na', color='blue', linestyle='--')
    plt.legend(loc='upper right')
    plt.title(f'L1_grads_values')
    plt.xlabel('Training Step')
    plt.ylabel('Gradients Value')
    plt.ylim()
    plt.savefig(f'L0_grads_values{i}.png')
    plt.show()

    plt.figure()
    plt.plot(values3, label='L1_FFN0_na', color='red', linestyle='--')
    plt.plot(values4, label='L1_FFN1_na', color='blue', linestyle='--')
    plt.legend(loc='upper right')
    plt.title(f'L1_grads_values')
    plt.xlabel('Training Step')
    plt.ylabel('Gradients Value')
    plt.ylim()
    plt.savefig(f'L1_grads_values{i}.png')
    plt.show()

    # plt.figure()
    # plt.plot(values5, label='L2_FFN0_na', color='red', linestyle='--')
    # plt.plot(values6, label='L2_FFN1_na', color='blue', linestyle='--')
    # plt.legend(loc='upper right')
    # plt.title(f'L1_grads_values')
    # plt.xlabel('Training Step')
    # plt.ylabel('Gradients Value')
    # plt.ylim()
    # plt.savefig(f'L2_grads_values{i}.png')
    # plt.show()

    # plt.figure()
    # plt.plot(values7, label='L3_FFN0_na', color='red', linestyle='--')
    # plt.plot(values8, label='L3_FFN1_na', color='blue', linestyle='--')
    # plt.legend(loc='upper right')
    # plt.title(f'L1_grads_values')
    # plt.xlabel('Training Step')
    # plt.ylabel('Gradients Value')
    # plt.ylim()
    # plt.savefig(f'L3_grads_values{i}.png')
    # plt.show()